### ISSUE TITLE
Not needed padding on tabs on dev version

### ISSUE THREAD

**Issue by lisovyk** [ericrayanderson/shinymaterial#10]
Sample:
```
library(shinymaterial)

ui <- material_page(
    material_tabs(
        tabs = c(
            "tab" = "first_tab",
            "tab" = "second_tab"
        )
    )
)
server <- function(input, output) {}
shinyApp(ui = ui, server = server)
```
On current dev version there is not intended(i guess?) padding on the material_tabs. See the sample above.
In the sample, there is a div with `col s12 offset-s0` class. It has `padding: 0 .75rem;` that causes tabs to  not fill the whole width of the page.

**Comment by ericrayanderson** [comment]
That was intended. I went back and forth on which way to do it. I figured most people would want things off the edges, at the cost of flexibility. But, that may not be the case.

**Comment by lisovyk** [comment]
Uh, I dont know. It doesn't seem good imo. Maybe that's only my preferences.

**Comment by jbkunst** [comment]
Hi everyone,

My 1 1/2 cents: In my particular case, I've changed previously the defaults in the package I maintain because IMHO it's better :sweat_smile: , but sometimes it's good be consistent with the library/framework/etc we're porting to R i.e. keep the defaults intact.

(https://github.com/jbkunst/highcharter/issues/272)

**Comment by ericrayanderson** [comment]
Padding has been removed (beginning with v_0.3.0).
