### ISSUE TITLE
Move js in maeterial_page to other place....

### ISSUE THREAD

**Issue by happyshows** [ericrayanderson/shinymaterial#3]
Hi,

I just took a look at the function, it seems weird to me that the js is embedded in this function, and without wrapping this around other material components, css won't work.

If you compare the natvie page function vs material, former one is pretty simple, and easy to embed.
fluidPage(h6(''))
material_page(h6(''))

There are two use cases moving js out of it will be beneficial:
1) when user needs to concatenate their own ui code and maybe pass to other language like javascript. I ran into the problem right now.
2) mix & match between UIs, instead of wrapping this function, maybe user just want to library the package and add the "grey lighten-4" to the div. and continue to use other components that's not yet available in shinymaterial.

maybe utilize some function like rintrojs::introjsUI() or shinyjs::useShinyjs() to include js.

**Comment by ericrayanderson** [comment]
I have not found a good way to implement the mix & match between UIs (some shiny inputs, some shinymaterial inputs) yet.

One of the problems I ran into:

 - The Materialize CSS library has CSS classes that overlap with Bootstrap (for example, they both use "btn" for buttons). If, for example, someone tried to include `shiny::actionButton()` in an app that loads Materialize CSS, the styling of the button would be affected.

Note * While the function `fluidPage(h6(''))` only returns a single div, it is doing more in the background. Running `fluidePage` (no `()`) in the console reveals that it is calling the function `bootstrapPage`. Running `bootstrapPage` in the console reveals that this is attaching the Bootstrap CSS library.

I think `material_page` is more comparable to `navbarPage`, since they both include a built in navbar.

Being able to mix and match would be optimal. However, I do think it might be strange for an app to have some elements of material design, but not all of them. Although, for your example of using `grey lighten-4`, that would make sense. But to do that I would say there is no need to use the `shinymaterial` package. In that case they could just load materialize css:
```r
shiny::includeCSS(
"https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css"
)
```

What do you think?


Do you have an example app for trying to:

> concatenate their own ui code and maybe pass to other language like javascript

I think it could make problem you are having more clear to me, and hopefully improve `shinymaterial` as a whole.

**Comment by happyshows** [comment]
for example, I want to build an htmlwidget that utilize the material switch component. It requires loading some value dynamically online (let's say the on label and off label strings) and then concatenate the strings in js + append it to a div id.
```
'<label for="example_switch">Switch</label>'+
'<div class="switch shiny-material-switch">'+
 '<label>'+
varaible_off+
'<input type="checkbox" id="example_switch"checked/>'+
'<span class="lever"></span>'+
varaible_on+
'</label>'+
'</div>'
```
if I need to include the material_page (to make the component working properly) I guess it will make the code chunk really messy.
Currently I'm using shinyWidgets material switch and it's dropdown button, but I do like the checkbox in your package and would like to use them together if possible.

**Comment by ericrayanderson** [comment]
Ah, I see what you are trying to do.

It looks like `shinyWidgets` is different than `shinymaterial` in that it has individual css files for each component. `switchInput` is calling `switchInput/css/bootstrap-switch.min.css`. 

To incorporate this feature would be a large undertaking, because right now I pull in `materialize.css`, which includes the CSS for all of the inputs.

I will definitely keep this in mind and try to see if there is a way of incorporating it.

**Comment by happyshows** [comment]
thanks.
