### ISSUE TITLE
Are material widgets compatible with fixed_page or fluid_page? 

### ISSUE THREAD

**Issue by tiannanz** [ericrayanderson/shinymaterial#54]
This might be a stupid question as I am new to R Shiny - but I wonder if material widgets can be incorporated into fixed_page/row or fluid_page/row? 

It wasn't working when I tried, and I guess it required material_page() to wrap the functions up? Thank you.

**Comment by ericrayanderson** [comment]
Material widgets are not compatible with `fluid_page` since `fluid_page` will use the Bootstrap CSS library, where as `material_page` uses the Materialize CSS library. Some widgets may work with `fluid_page`, but it was not intended to be use with that. `shinymaterial` also has functions like `material_row` which stand in place of `fluid_row`.
